### PR TITLE
add cuteblog template pico

### PR DESCRIPTION
**Pull request by mesinkasir**
add cuteblog template pico cms

### CODE REVIEW

**Comment by mayamcdougall** [comment]
Hi again. 👋🏻

Sorry this has taken so long...*again*.  Still running behind on things. 😅 

If you would, can I get you to make your fullsize images `1440x900`, not `1440x990`?

I probably should have said something last time instead of quietly cropping them. 😓

I'd do it myself, but since you've included these nice promotional images instead of raw screenshots, there's no way I can crop them without them looking bad (and, of course, I'd feel bad since you put that much work into them).

Thanks. 😁

**Comment by mesinkasir** [comment]
> Hi again. 👋🏻
> 
> Sorry this has taken so long..._again_. Still running behind on things. 😅
> 
> If you would, can I get you to make your fullsize images `1440x900`, not `1440x990`?
> 
> I probably should have said something last time instead of quietly cropping them. 😓
> 
> I'd do it myself, but since you've included these nice promotional images instead of raw screenshots, there's no way I can crop them without them looking bad (and, of course, I'd feel bad since you put that much work into them).
> 
> Thanks. 😁

Oh oke.. i will fix it 😉

**Comment by mesinkasir** [comment]
> Huh... it looks like you did _just_ crop it.
> 
> I could have done that, lol. 😅
> 
> I just thought you might have to reposition some of the layers.
> 
> Anyway, it's probably my fault you had the resolution wrong. On your first submission, I wrote the resolution then ~used strikethrough~ on my entire comment, which made ~`1440x900`~ really hard to read. 😓
> 
> I'll get this merged in, thanks for your contribution. ❤️
> 
> By the way, on an unrelated note:
> 
> We're getting ready to release Pico 3.0 soon, which includes updated dependencies.
> 
> There's a change in Twig (we're going from `1.x` to `3.x`), where `if` statements can no longer be combined with `for` loops.
> 
> Before you could use:
> 
> ```
> {{ for page in pages if not page.hidden }}
> {{ endfor }}
> ```
> 
> And now that must be:
> 
> ```
> {{ for page in pages }}
>   {{ if not page.hidden }}
>   {{ endif }}
> {{ endfor }}
> ```
> 
> There's a few other minor incompatibilities too, but this is the main one for Theme developers.
> 
> Since we used some `for/if` statements in the Default Theme, literally every theme that followed our example will have to be updated. 🤦🏻‍♀️
> 
> I haven't looked at your Twig code at all, but since you seem to be actively developing more themes, I thought you'd want to know, that way you can make changes if needed. There's no release date for Pico 3.0 yet, it'll just be out "when it's done".
> 
> Hopefully this isn't too much information. I don't know how good your English is, but I noticed it's not your first language. Just let me know if I could be explaining anything better and I will try. 😅❤️

Wow, that's cool info.. I can't wait for the newest version of pico to be released. 😍😍.
And yes, I often use google translation to communicate 🤣🤣🤣

**Comment by mayamcdougall** [comment]
>Wow, that's cool info.. I can't wait for the newest version of pico to be released. 😍😍.

Well, don't get *too* excited. Even though we're calling it "3.0", there's not going to be anything major like new features. (😞)

It's just a maintenance release because 2.0's older dependencies aren't compatible with PHP 8.0+ (which is a big problem going forward).  It's being called "3.0" instead of "2.2" though because it will break compatibility in some places.

Pico's always tried to remain 100% backwards compatible, even with some of the oldest Themes and Plugins.  But this time because of the changing dependencies, that won't be true (and there's nothing we can do about it).

So calling it "3.0" is an effort to let people know "this update could break things".

>And yes, I often use google translation to communicate 🤣🤣🤣

No worries, lol. 😂 

Just let me know if I ever need to be more clear. 😉

**Pull request merged**
