### PR TITLE
Add pico-users plugin

### PR DESCRIPTION
**Pull request by nliautaud**

### CODE REVIEW

**Comment by nliautaud** [comment]
Thanks for the review ! 
- Improved passwords session security (nliautaud/pico-users#6)
- Added support of password_hash and password_compat, hash used as fallback (nliautaud/pico-users#7)

**Comment by nliautaud** [comment]
- fixed nliautaud/pico-users#8
- hash removed, password_compat shipped with plugin (nliautaud/pico-users#7)

**Comment by smcdougall** [comment]
@nliautaud I did some brief testing and everything seems to work right.

One suggestion I'd have if you continue to develop this is to hide "403.md" from Pico's `pages` array, otherwise, using a custom 403 page will result in it showing in Pico's navigation. :confounded:
(@PhrozenByte not sure if you have any suggestions here.)

That's not really a criticism, just something I noticed. :wink:

Anyway, great work!  I'll get this up on the website for you. :tada:

**Comment by nliautaud** [comment]
Thanks for the reviews and merge ! 🍾
There seems to be an issue with the markdown rendering though :/ Tell me if there is anything I can fix myself.

Hiding 403 pages is a great suggestion, I'm surprised I didn't see that at the time. I'll add an issue.

I didn't planned to take much time on it, considering that it may become irrelevant with next releases of Pico or admin plugins (it was 2013, been a long time since I took a look though), but I'll maintain it at least :).

**Comment by smcdougall** [comment]
> There seems to be an issue with the markdown rendering though

In your Submission file?  You just forgot the `.md` extension is all.  I fixed it a few minutes after merging this, so you may have seen it before I pushed the fix.  It's all set now. 😉 👍

**Pull request merged**
