### PR TITLE
Add pico-pages-list plugin

### PR DESCRIPTION
**Pull request by nliautaud**

### CODE REVIEW

**Comment by nliautaud** [comment]
Hi, thanks for the review(s).

Did I replace directly the Pico pages array somewhere ? I think I didn't get what you mean, but my PHP is rusty.

About what should be done with it, I didn't follow the development of Pico and for now I'm mainly updating my 4 years old plugins, so I let you decide what you think is best :)
Do you have a link to the will-be official plugin ?

That's great that there will be a way to hide pages in Pico core. Allowing to hide specific paths from the plugin output may be useful for managing separately this page list though. Actually a best way to do it would have been trough a twig function, to allow multiple concurrent outputs, ex `{{ pages_list.exclude('foo/bar/', 'secrets/') }}` or `{{ pages_list.only('category/') }}` (even if it's possible trough css for now). I may add an issue.

**Comment by PhrozenByte** [comment]
> Did I replace directly the Pico pages array somewhere ?

Oh, my fault, I was wrong. You don't do this.

However, it might be a good idea to pass `PicoPagesList::$pages` as twig variable, not just the created HTML.

> Do you have a link to the will-be official plugin ?

I didn't create the repo yet, unfortunately don't have much time for Pico lately.

> Allowing to hide specific paths from the plugin output may be useful for managing separately this page list though.

Sounds great! 👍

**Comment by nliautaud** [comment]
Hello, for info I've made some changes. [README.md](https://github.com/nliautaud/pico-pages-list/blob/master/README.md) / [commits](https://github.com/nliautaud/pico-pages-list/commits/master)
- default output with `{{ PagesList.html }}`
    - added output filtering trough twig instead of config with `{{ PagesList.html(options) }}`
    - added inclusive/exclusive filtering
    - added css utility classes
- exposed the nested array trough `{{ PagesList.items }}`, added example of recursive twig macro
- derived the page items from the Pico pages array, to give access to pages data in the nested array
- refactoring

----
A small thought : 

For an official plugin, a cleaner interface allowing access to both a flat and a nested array, that can be both filtered and rendered, may be trough twig filters. Something like :
```twig
{{ pages }} // flat list of pages
{{ pages | nested }} // nested list of pages/dirs
{{ pages | html_tree }} // render the given array
{{ pages | only: 'foo/bar' }} // filter the given array
{{ pages | exclude: 'foo/bar', 'other' }} // filter the given array
// ex :
{{ pages | nested | exclude: 'foo/bar', 'other' | html_tree }}
```
I didn't implemented that as I'm not sure of the future of this thing 😃

**Comment by PhrozenByte** [comment]
Pico's official page tree plugin won't implement much more than building the page tree, everything else is up to the theme developer. So, extending your plugin's functionality as suggested might be a good idea to differentiate it from Pico's official plugin.

By the way: You [shouldn't pass `$this` to Twig](https://github.com/nliautaud/pico-pages-list/blob/2eea787f0ac4966a597aa832475973df460b2e7d/PicoPagesList.php#L58), since this allows plugin developers to call arbitrary public methods of both your plugin class and Pico (and not just `.html` and `.items`). Use multiple twig variables or a twig function, filter or tag instead. https://twig.symfony.com/doc/1.x/advanced.html is a good starting point for this :smiley:

**Comment by nliautaud** [comment]
Did the major changes, documented things and did a debug pass :) See PR above.

**Comment by PhrozenByte** [comment]
This definitely differentiates your plugin from Pico's official plugin, or to put it another way, your plugin is way more powerful than our official one and all of my concerns have been addressed. There are just some minor suggestions in https://github.com/nliautaud/pico-pages-list/pull/5#pullrequestreview-71611567, nothing significant. Great work @nliautaud! 👍 

@smcdougall: As always, I neither tested the plugin nor checked the submission file, I was just checking the plugin's source code. What do you think about this one? 😃

**Comment by PhrozenByte** [comment]
This PR got kinda abandoned... Time flies :facepalm: :unamused: Sorry!

The plugin is pretty commonly used, so I merged it nevertheless there is still a improvement PR pending. Would love to see if you check https://github.com/nliautaud/pico-pages-list/pull/18 and possibly merge it. Great work @nliautaud and thanks, you did a great work here! :heart:

**Comment by nliautaud** [comment]
No problem, same thing here. I won't be able to take a look and test the PR for a few months, so if you confirm that you checked it I'll merge it !

**Comment by PhrozenByte** [comment]
Just tested my PR (wow this is soooo old) and seems to work just fine :+1:

**Comment by nliautaud** [comment]
Done 👍

**Comment by PhrozenByte** [comment]
There went something wrong, no idea how this could happen. :unamused: Sorry! Please refer to https://github.com/nliautaud/pico-pages-list/pull/25 @nliautaud

**Pull request merged**
