### PR TITLE
Submission: Astronot Pico Theme

### PR DESCRIPTION
**Pull request by mesinkasir**

### CODE REVIEW

**Comment by mayamcdougall** [comment]
@PhrozenByte How do we feel about Themes targeting `api_version: 4` right now?

As far as I know, there's no real *benefit* to doing this, right?

I don't know how older versions of Pico react to "future" API versions. 🤔

We haven't really talked about that much.  In the themes I've been updating for 3.0, I've been specifically sticking with api 3 to maintain Pico 2.0 compatibility.

@mesinkasir `pico-theme.yml` isn't really *intended* to be edited by the user (unless they're actually *modifying* the theme).  That makes this a bit of an edge case while we're still finishing 3.0.

> "you can change api version with your pico api version on themes/astronot/pico-theme.yml"

Having a note explaining this isn't my preferred solution here...

Depending on how it impacts Pico 2.0, and what @PhrozenByte has to say, I *might* request that you change it back to `api_version: 3`, since it shouldn't make any real difference in Pico 3.0 either way.

That way it will be compatible with either Pico 2 or 3, without requiring modifications from the user. 😉

But I don't know, maybe this is a non-issue and Pico 2.0 doesn't actually care. 🤷🏻‍♀️

**Comment by PhrozenByte** [comment]
I'd always recommend updating to the latest version as soon as possible (i.e. requiring API version 4 is fine) :+1: However, we shouldn't merge it until we actually release API version 4 then :see_no_evil:

**Comment by mayamcdougall** [comment]
Oh, also `widescreen: false` is just a config option for the Default Theme, which makes the `body` load different CSS styles:

```twig
<body{% if config.theme_config.widescreen %} class="widescreen"{% endif %}>
```

You can remove that from `pico-theme.yml` if you're not using it for anything.

Same goes for the meta items `Logo: logo`, `Tagline: tagline` and `Social: social`.  If you're not using them in your theme, feel free to remove them.

They're not hurting anything.  Just giving some development tips. 😉

**Comment by mayamcdougall** [comment]
@PhrozenByte That doesn't *really* answer my question though.  How does Pico 2.0 react to "future" API versions?

Does it break (eg, "I can't find the API v4 code, so I'll just crash") or does it just fall back to the most "current" version (eg "API version is >= 3, so we're good").  This might actually be more of a question about PicoDeprecated, but whatever, lol.

Briefly looking over the code, it *seems* like it only checks for a *lower* version anyway.  So I guess I could have answered that myself. 😅 

So even if it's not the best idea...

Since there aren't any major changes, it shouldn't be an issue to just overlook this for now.  If someone with Pico 2.0 downloads this in the meantime, they'd likely be none the wiser about it.

So, I guess maybe I'll just leave it up to @mesinkasir then.  If you want to officially "support" both Pico 2.0 and 3.0, go with the older `api_version` for now.  If not, it probably doesn't matter much anyway.  It seems like Pico 2.0 won't know any better.

Come to think of it, you probably *developed* this on Pico 2.0... so this whole thought experiment was pointless. 🤦🏻‍♀️ 

In a few weeks (or whenever 3.0 is done 😅) it won't be an issue anyway.

---

Also, I'm noticing now that you've included `lib/pico.php` in your repo. And it's mentioned in your readme so this doesn't seem to be an accident. 🤔

I'm not sure why you've included it here, as unlike your `webapp` branch, your `main` branch isn't a full starter project.

Either way, I prefer Themes to just be *Themes*.  Full "Starter Project" bundles tend to go out-of-date quickly.  I don't mind you having it in your separate `webapp` branch, that's fine.

I just like users to have an easy time downloading the Theme itself when they try (with no extra baggage, like an unexpected `pico.php`).

Even though we clearly say that these are "**community-developed** themes", many users still mistakenly think that they're *officially* provided. 🙄 🤦🏻‍♀️

So, I might be a little too strict about things, but mostly I just feel some responsibility in making sure our users have a good experience. 😉

**Comment by PhrozenByte** [comment]
> @PhrozenByte That doesn't _really_ answer my question though. How does Pico 2.0 react to "future" API versions?
> 
> Does it break (eg, "I can't find the API v4 code, so I'll just crash") or does it just fall back to the most "current" version (eg "API version is >= 3, so we're good"). This might actually be more of a question about PicoDeprecated, but whatever, lol.

Pico itself will accept any theme (and plugin) with a matching or newer API version, i.e. Pico 2.0 will happily accept API version 4 (what probably is a bad thing thinking about it :see_no_evil:). However, PicoDeprecated won't: PicoDeprecated will try to load a compatibility plugin for API version 4, what will fail for obvious reasons. So, no, in the end you can't use a API version 4 theme with Pico 2.0.

**Comment by mesinkasir** [comment]
Hi..
oh sorry for my mistake 🙈, because i tried clone from one of pico3 repo yesterday, ok i will fix it to current version.
thank you for the information and explanation

**Comment by mayamcdougall** [comment]
Oh, wow, it's been 6 days already. 😓

I had a reply written for this... but it was a bit long and rant-y, so I decided to scrap it.

---
> However, PicoDeprecated won't

@PhrozenByte Gotcha.  I thought I remembered seeing code in PicoDeprecated that specifically tries to match the API version to a specific compatibility function. 😉

---

One of the key points I wanted to touch on though, was that the Astronot Demo Site specifically included instructions on how to modify Pico to *force* an `api_version`. 🤦🏻‍♀️ 

That's not really okay, and I feel I have to draw a line there on what is and isn't allowed in the Gallery. 🤔

@mesinkasir, it seems like you're already on the right track, but my suggestions are:

- Target `api_version: 3`, as the lower version won't make any actual difference to the functionality of your theme.
- Please remove the instructions on *modifying* Pico from your demo site.  This isn't something we want to encourage users to do.
- There's no reason that I can see to include `lib/pico.php` in your `main` repo branch.  Please keep the main branch clean, that way users can more easily install *only* the theme files.  (And as I said above, your `webapp` branch with the complete project is perfectly fine, I just don't want users to accidentally override any of Pico's files while they're trying to install *just* the theme.)

Let me know if there's anything I can help with.  It shouldn't be too difficult to make the changes needed.

**Comment by mesinkasir** [comment]
> Oh, wow, it's been 6 days already. 😓
> 
> I had a reply written for this... but it was a bit long and rant-y, so I decided to scrap it.
> 
> > However, PicoDeprecated won't
> 
> @PhrozenByte Gotcha. I thought I remembered seeing code in PicoDeprecated that specifically tries to match the API version to a specific compatibility function. 😉
> 
> One of the key points I wanted to touch on though, was that the Astronot Demo Site specifically included instructions on how to modify Pico to _force_ an `api_version`. 🤦🏻‍♀️
> 
> That's not really okay, and I feel I have to draw a line there on what is and isn't allowed in the Gallery. 🤔
> 
> @mesinkasir, it seems like you're already on the right track, but my suggestions are:
> 
> * Target `api_version: 3`, as the lower version won't make any actual difference to the functionality of your theme.
> * Please remove the instructions on _modifying_ Pico from your demo site.  This isn't something we want to encourage users to do.
> * There's no reason that I can see to include `lib/pico.php` in your `main` repo branch.  Please keep the main branch clean, that way users can more easily install _only_ the theme files.  (And as I said above, your `webapp` branch with the complete project is perfectly fine, I just don't want users to accidentally override any of Pico's files while they're trying to install _just_ the theme.)
> 
> Let me know if there's anything I can help with. It shouldn't be too difficult to make the changes needed.

yes i have deleted all the sites and the instructions are no longer there, maybe later i will rebuild with pico version 3 🙏

**Pull request closed without merging**
