### PR TITLE
3colors theme

### PR DESCRIPTION
**Pull request by psic**

### CODE REVIEW

**Comment by mayamcdougall** [comment]
Hello,

Sorry for taking a few days to reply.  Let's see if we can get this submission ready-to-go. 😄

There's a few minor issues that need to be addressed before I can merge this.  There's a fair number of typos in your YML (`.md` file), but I can sort those out for you easier than I can list them all.  They're all minor things, but YML can be picky. 🙄

The *big* issue is I need you to change the resolution of your images.

Thumbnails *must* be `270x220px`, while Fullsize images should be `1440x900px`.

Unfortunately, our site gallery is a little picky about this.  While there are some non-conforming fullsize images in there (that I should really go through and fix in the future), the preferred full-size resolution is still `1440x900px`.

I'm not sure how best to approach your mobile screenshots with this limitation.  I think my suggestion would be to create a kind of "promotional showcase" type image with multiple mobile screenshots against a background.  I could help with this if needed.

If it were as simple as cropping/resizing the images, I'd just do it for you, but the responsive nature of a web page makes that a little more annoying (as a cropped image would cut off a lot of content and just wouldn't look very good).

So, if you can provide some new images, I can take it from there. 😄

---

Sorry to go on for so long. I write essays, not replies. 😒

Just want to touch on a few unrelated things before I go.

First, thanks for noticing that URL issue in the Contribute Tile.  Not sure if this was a hold-over from when the website was still in the regular repo, or if it was just a mistake from the get-go. 🤔

I noticed you submitted some Plugins as well.  Plugin submissions have to go through @PhrozenByte, so it may be awhile before he has time to review them.  In the meantime, feel free to add them to the list of community plugins on the [Pico Wiki](https://github.com/picocms/Pico/wiki/Pico-Plugins).

I took a look at your 3 Colors Demo site and its color randomizer.  Randomizing the colors makes for a neat demo, but can also lead to some really *awful* colors if the visitor has bad luck. 😂

If it's something that bugs you too, maybe you could come up with some pre-created color palettes that work well, and randomly pick from one of those every time.  If you wanted to, I know there are plenty of color palette picking websites you could use to get started.  It was just a thought I had, so I thought I'd share. 😉

On that note, if you ever want to get rid of that extra `||` at the end of your NavBar, try this:

```
#nav ul li:last-child a {
  border-right: none;
}
```

---

Alright, I'll quit my commentary already. 😅

As always, thank you for your submission. ❤️

Hope to hear back from you with those images soon.

**Comment by psic** [comment]
hard for me to take a  `1440x900px` screenshot on a `1366x768` screen. I will be very careful to keep the same proportion, and have the right size of the thumbnail. Good idea for the mobile screenshot. It will be done.

>I took a look at your 3 Colors Demo site and its color randomizer. Randomizing the colors makes for a neat demo, but can also lead to some really awful colors if the visitor has bad luck

There are never awful color  ? ;) . It was for test purpose, but I will do my randomize, less random.

> On that note, if you ever want to get rid of that extra || at the end of your NavBar, try this:

Thanks, I don't want to get rid of the last || of the navBar.

Thanks for your reply/essay. (few days for a PR, it is not sol long).

**Comment by mayamcdougall** [comment]
> hard for me to take a 1440x900px screenshot on a 1366x768 screen.

Oh, well, in that case just feel free to do something of the right aspect ratio and just scale it up.  It's less of a hard requirement and more "I didn't make the themes gallery play nice with tall images". 😅

Also consistency is nice, so I like them to all be *about* the same.

> There are never awful color ? ;) . It was for test purpose, but I will do my randomize, less random.

Lol. It was just a thought I had, nothing you *have* to do.  Just an idea of how you could better showcase your work. 😜

> I don't want to get rid of the last || of the navBar.

Okay, that's cool. 👌

It bugs the *heck* out of me, but that's just my personal preference, lol.

> few days for a PR, it is not so long

Maybe not, but it had been staring at me from my inbox... 👀 😅

**Comment by mayamcdougall** [comment]
> It bugs the heck out of me, but that's just my personal preference, lol.

Oh wait, I get it now. It plays nicely with the drop down menu. I hadn't noticed that connection before. 🤔😅

**Comment by psic** [comment]
can make a 1440x900 screenshot using Firefox dev tools :)
Hope theses change are all good. Say me ?
I got a slide theme and a blog theme / template project for you inbox!

**Comment by mayamcdougall** [comment]
All set. 😁

Thanks again for your contribution. ❤️

(Also, if I knew you were just going to use your demo site for the screenshots, I could have just done that for you.  I thought you had another site for it like in your original screenshots. 😅)

**Comment by psic** [comment]
My first site was a loreipsum ~shit~ stuff. Now, I fill it with some of the ReadMe info, and I think it is more accurate.

**Comment by mayamcdougall** [comment]
Nothing wrong with some good Lorem Ipsum "stuff" though.  It's always good screenshot filler too. 😉

**Pull request merged**
