### PR TITLE
Add pico-pages-images plugin

### PR DESCRIPTION
**Pull request by nliautaud**

### CODE REVIEW

**Comment by nliautaud** [comment]
Fixed nliautaud/pico-pages-images#1 and nliautaud/pico-pages-images#2

**Comment by smcdougall** [comment]
When trying this plugin, I got a PHP Notice:

`Notice: Undefined offset: 4 in [Pico Root Dir]/plugins/PicoPagesImages.php on line 85`

This is repeated for every image in the corresponding folder.

@PhrozenByte Is this an issue?  If so, how can @nliautaud fix it?  Obviously this is also with PHP errors turned on.  Haven't tested with them off, but assuming they wouldn't show.

Other than that, it seems to work as intended.  I'll merge this if @PhrozenByte gives the okay, or if you fix the issue. :smiley:

---

On a side note, ~~you may want to fix~~ (submitted a PR) your readme where it mentions `http://mysite.com/content/foo/bar/bar-image_01.jpg` in the table.  Placing images in the content folder won't work with Pico's default security settings.  You use `images/` for everything else, so you should probably change it to that. :wink:

Actually, it seems like you may have just accidentally swapped that URL with the line above, where it says "corresponding to the page `http://mysite.com/images/foo/bar`".

I submitted a PR to fix this.  If I'm just reading/interpreting it wrong, feel free to ignore this.

**Comment by nliautaud** [comment]
That's strange, the undefined offset is related to https://github.com/nliautaud/pico-pages-images/issues/2, I thought it was fixed 🤔

Thanks for the PR ! The previous version of this plugin was locating images next to pages, in content. It was actually the point of it. See https://github.com/nliautaud/pico-pages-images/tree/f38b7f2cf988ab52ee9b9b0196d46fb94c802c0c#files-location
Defining another location for images (`images/`, cdn...) was an alternative option. I had to reverse this behavior for Pico 1.x, according to the security settings as you said.

**Comment by PhrozenByte** [comment]
Hmm... No idea about this bug @smcdougall, this should be impossible due to `array_pad()`. What PHP version? Are you sure you tried the latest version?

**Comment by smcdougall** [comment]
I'm running PHP 7.1.9, and looking at my copy of `PicoPagesImages.php`, it *does* use `array_pad` on line 85, so it's definitely the latest copy.

**Comment by nliautaud** [comment]
The `Notice: Undefined offset: 4` issue should be fixed, see nliautaud/pico-pages-images/issues/4

**Comment by PhrozenByte** [comment]
The patch sounds reasonable. Great work @nliautaud! 👍 

@smcdougall: Do you want to test the plugin again? I still didn't test it nor checked the submission file. Thanks! 😃

**Comment by PhrozenByte** [comment]
Sorry for the unacceptable late response @nliautaud :unamused:

You did a great job here! :+1:

**Pull request merged**
